name    'netmanagers-bind'
version '2.0.10'
author  'Javier Bertoli'
license 'Apache2'
project_page 'http://www.netmanagers.com.ar'
source  'https://github.com/netmanagers/puppet-bind'
summary 'Puppet module for bind'
description 'This module installs and manages bind9 nameserver. Check README for details.'
dependency 'puppetlabs/stdlib', '>=4.1.0'
dependency 'puppetlabs/concat', '>=1.0.0'
dependency 'example42/puppi', '>= 2.0.0'
dependency 'example42/monitor', '>= 2.0.0'
